# Generated by Django 4.2.2 on 2023-07-07 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_user_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_image",
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
