# Generated by Django 4.2.2 on 2023-07-14 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_remove_user_user_image_userimage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userimage",
            name="user",
        ),
        migrations.AddField(
            model_name="userimage",
            name="user",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
