# Generated by Django 4.2.2 on 2023-07-04 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("review", models.TextField(max_length=3000)),
                ("published_at", models.DateField(auto_now=True)),
                (
                    "rate",
                    models.IntegerField(
                        choices=[
                            (0, "Note 0"),
                            (1, "Note 1"),
                            (2, "Note 2"),
                            (3, "Note 3"),
                            (4, "Note 4"),
                            (5, "Note 5"),
                            (6, "Note 6"),
                            (7, "Note 7"),
                            (8, "Note 8"),
                            (9, "Note 9"),
                            (10, "Note 10"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="games.game",
                    ),
                ),
            ],
        ),
    ]
