# Generated by Django 4.2.2 on 2023-07-04 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("genders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300, unique=True)),
                ("descripition", models.TextField(max_length=1000)),
                ("game_logo", models.CharField(max_length=300)),
                ("made_by", models.CharField(max_length=200)),
                ("users_avaliations", models.FloatField()),
                (
                    "genders",
                    models.ManyToManyField(related_name="games", to="genders.gender"),
                ),
            ],
        ),
    ]
