# Generated by Django 4.2.2 on 2023-07-05 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0002_remove_game_descripition_game_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="users_avaliations",
            field=models.FloatField(default=0, editable=False),
        ),
    ]
