# Generated by Django 4.2.2 on 2023-07-07 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0004_rename_name_game_name_game"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="users_avaliations",
        ),
    ]
